### ISSUE TITLE
Question regarding the correlation rotio code for continuous and categorical variables

### ISSUE THREAD

**Issue by tamasbarat** [shakedzy/dython#87] opened 2021-07-13 11:19 UTC
Hey Shaked, 

I am currently working on my thesis for which I aim to predict the routes of NFL pass receivers. Basically, I am dealing with a typical classification problem. As I have continuous and categorical features in my training data, I would really like to use the code you provided for this case as it would help me investigate the potential predictive power of features in regards to my target variable 'route'. However, I am struggling to get the code running with my data. I am new to Python and find it difficult to see where I need to define objects or plug in the specifics of my dataset into your code. Essentially, all I am asking for is an indication of what I need to plug in where. Sorry for this micro-management-like question, but I could not help myself.

Here is my dagtaframe
![image](https://user-images.githubusercontent.com/80772765/125443152-646ce595-754e-4cdb-a266-a17d164c82ff.png)

**Comment by shakedzy** [comment] 2021-07-13 18:03
Closing, as this is a duplicate of issue #88

**Closed by shakedzy** 2021-07-13 18:03 UTC
Labels: question
